# general
root: results/nh3
run_name: legato_L1_rho_0_025
l_max: 1
with_sam: true
rho: 0.025 
early_stopping_patiences:
  validation_loss: 100
early_stopping_delta: 
  validation_loss: 0.005
seed: 123455
dataset_seed: 123456
append: true
default_dtype: float32

# -- network --
model_builders:
 - allegro.model.Allegro
 # the typical model builders from `nequip` can still be used:
 - PerSpeciesRescale
 - ForceOutput
 - RescaleEnergyEtc

# cutoffs
r_max: 6.0
avg_num_neighbors: auto

# radial basis
BesselBasis_trainable: true
PolynomialCutoff_p: 7   

# symmetry
parity: o3_full   

# Allegro layers:
num_layers: 3
env_embed_multiplicity: 32
embed_initial_edge: true

two_body_latent_mlp_latent_dimensions: [32, 64, 128]
two_body_latent_mlp_nonlinearity: silu
two_body_latent_mlp_initialization: uniform

latent_mlp_latent_dimensions: [128]
latent_mlp_nonlinearity: silu
latent_mlp_initialization: uniform
latent_resnet: true

env_embed_mlp_latent_dimensions: []
env_embed_mlp_nonlinearity: null
env_embed_mlp_initialization: uniform

# - end allegro layers -

# Final MLP to go from Allegro latent space to edge energies:
edge_eng_mlp_latent_dimensions: [32]
edge_eng_mlp_nonlinearity: null
edge_eng_mlp_initialization: uniform

# -- data --
dataset: ase                                                                   
dataset_file_name: dataset/nh3/optpbe_all.xyz                      # path to data set file
key_mapping:
    forces: forces
    stress: virial
    energy: total_energy

ase_args:
  format: extxyz

# A mapping of chemical species to type indexes is necessary if the dataset is provided with atomic numbers instead of type indexes.
chemical_symbol_to_type:
  H: 0
  N: 1

# logging
wandb: true
wandb_project: allegro
verbose: info
log_batch_freq: 10

# training
n_train: 4500
n_val: 500
batch_size: 4
validation_batch_size: 2
max_epochs: 1500
learning_rate: 0.002
train_val_split: random
shuffle: true
metrics_key: validation_loss

# use an exponential moving average of the weights
use_ema: true
ema_decay: 0.99
ema_use_num_updates: true

# loss function
loss_coeffs:
  forces: 1.
  total_energy:
    - 1.
    - PerAtomMSELoss

# optimizer
optimizer_name: Adam
optimizer_params:
  amsgrad: false
  betas: !!python/tuple
  - 0.9
  - 0.999
  eps: 1.0e-08
  weight_decay: 0.

metrics_components:
  - - forces
    - mae 
  - - forces
    - rmse
  - - forces
    - rmse
    - PerSpecies: True
      report_per_component: False
  - - total_energy
    - rmse 
  - - total_energy
    - rmse
    - PerAtom: True                        # if true, energy is normalized by the number of atoms

# lr scheduler, drop lr if no improvement for 50 epochs
lr_scheduler_name: ReduceLROnPlateau
lr_scheduler_patience: 50
lr_scheduler_factor: 0.5

early_stopping_lower_bounds:
  LR: 1.0e-5
