# !! PLEASE NOTE: `minimal_eng.yaml` is meant as a _minimal_ example of a tiny, fast
#                 training that can be used to verify your nequip install,
#                 the syntax of your configuration edits, etc.
#                 These are NOT recommended hyperparameters for real applications!
#                 Please see `example.yaml` for a reasonable starting point.

# general
root: results/aspirin
run_name: minimal_eng
seed: 123
dataset_seed: 456

# network
# The default is to build a model with forces, so we need to specify
# `model_builders` to get one without forces. This list is the default,
# except without the `ForceOutput` builder that makes a force+energy
# model out of an energy model:
model_builders:
  - SimpleIrrepsConfig  # make configuration easier
  - EnergyModel         # the core nequip model
  - PerSpeciesRescale   # per-species/per-atom shift & scaling
  - RescaleEnergyEtc    # global scaling
# options for the model:
num_basis: 8
r_max: 4.0
l_max: 2
parity: true
num_features: 16

# data set
# the keys used need to be stated at least once in key_mapping, npz_fixed_field_keys or npz_keys
# key_mapping is used to map the key in the npz file to the NequIP default values (see data/_key.py)
# all arrays are expected to have the shape of (nframe, natom, ?) except the fixed fields
# note that if your data set uses pbc, you need to also pass an array that maps to the nequip "pbc" key
dataset: npz                                                                       # type of data set, can be npz or ase
dataset_url: http://quantum-machine.org/gdml/data/npz/aspirin_ccsd.zip             # url to download the npz. optional
dataset_file_name: ./benchmark_data/aspirin_ccsd-train.npz                         # path to data set file
key_mapping:
  z: atomic_numbers                                                                # atomic species, integers
  E: total_energy                                                                  # total potential eneriges to train to
  F: forces                                                                        # atomic forces to train to
  R: pos                                                                           # raw atomic positions
npz_fixed_field_keys:                                                              # fields that are repeated across different examples
  - atomic_numbers

chemical_symbols:
  - H
  - O
  - C

# logging
wandb: false
wandb_project: aspirin
# verbose: debug

# training
n_train: 5
n_val: 5
batch_size: 1
max_epochs: 10

# loss function
loss_coeffs: total_energy

# optimizer
optimizer_name: Adam
