language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install 'coverage<4.0.0'; fi
  - pip install coveralls

script: coverage run --source lammpsdoc setup.py test

after_success:
    coveralls
